<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>WowVmMonitor</Product>
    <Company>WowVmMonitor</Company>
    <AssemblyName>WowVmMonitor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WowVmMonitor.App\WowVmMonitor.App.csproj" />
    <ProjectReference Include="..\WowVmMonitor.Core\WowVmMonitor.Core.csproj" />
    <ProjectReference Include="..\WowVmMonitor.Infrastructure\WowVmMonitor.Infrastructure.csproj" />
  </ItemGroup>

</Project>
